### ISSUE TITLE
AdalServiceException: AADSTS50079

### ISSUE THREAD

**Issue by abhilashr1** [juunas11/aspnetcore2aadauth#6]
I have an AD which uses MFA. Sometimes, when I login, MFA doesn't prompt. This causes the app to fail with the below error: 

Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS50079: The user is required to use multi-factor authentication.
Trace ID: 5c8ce2fc-1720-45c1-899a-0a6d0e965600
Correlation ID: e421d7f3-0160-4431-bc41-d675aa4007e8
Timestamp: 2018-03-16 15:03:39Z ---> System.Net.Http.HttpRequestException:  Response status code does not indicate success: 400 (BadRequest). ---> System.Exception: {"error":"interaction_required","error_description":"AADSTS50079: The user is required to use multi-factor authentication.\r\nTrace ID: 5c8ce2fc-1720-45c1-899a-0a6d0e965600\r\nCorrelation ID: e421d7f3-0160-4431-bc41-d675aa4007e8\r\nTimestamp: 2018-03-16 15:03:39Z","error_codes":[50079],"timestamp":"2018-03-16 15:03:39Z","trace_id":"5c8ce2fc-1720-45c1-899a-0a6d0e965600","correlation_id":"e421d7f3-0160-4431-bc41-d675aa4007e8","claims":"{\"access_token\":{\"capolids\":{\"essential\":true,\"values\":[\"59866338-815e-41e6-9613-0ec6218e5c3d\"]}}}","suberror":"basic_action"}
   --- End of inner exception stack trace ---
   at Microsoft.IdentityModel.Clients.ActiveDirectory.HttpClientWrapper.<GetResponseAsync>d__30.MoveNext()
   --- End of inner exception stack trace ---
   at Microsoft.AspNetCore.Authentication.RemoteAuthenticationHandler`1.<HandleRequestAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.<Invoke>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.AspNetCore.Session.SessionMiddleware.<Invoke>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>d__6.MoveNext()
	ErrorCode: interaction_required
	StatusCode: 400

**Comment by juunas11** [comment]
Oh that's weird. Is that happening when you get redirected back to the app? I'm assuming it occurs when the app tries to exchange the code for the tokens.

**Comment by abhilashr1** [comment]
It does not happen all the time. Just when Azure bypasses MFA sometimes.

**Comment by juunas11** [comment]
Seems like a bug in AAD to me.. How could it let you sign in but then require MFA? I'll try to ask from the AAD guys when I have a chance.

**Comment by abhilashr1** [comment]
Thanks! I'll ask around as well.

**Comment by abhilashr1** [comment]
I managed to resolve this. The issue was with Azure AD not performing MFA sporadically. I had a word with the Azure AD admin and when my application was added to conditional access policy where MFA was always required, the issue was resolved.
